export const SCHEMA_V1 = `
CREATE TABLE IF NOT EXISTS wallets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  address TEXT NOT NULL UNIQUE,
  encrypted_private_key TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rpc_nodes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL UNIQUE,
  priority INTEGER NOT NULL DEFAULT 1,
  is_active INTEGER NOT NULL DEFAULT 1,
  latency_ms INTEGER DEFAULT 0,
  last_checked DATETIME
);

CREATE TABLE IF NOT EXISTS contracts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  address TEXT NOT NULL UNIQUE,
  mint_function TEXT NOT NULL DEFAULT 'mint(uint256)',
  mint_price TEXT NOT NULL DEFAULT '0.0',
  quantity INTEGER NOT NULL DEFAULT 1,
  gas_limit TEXT NOT NULL DEFAULT '300000',
  max_fee_per_gas TEXT NOT NULL DEFAULT '5.0',
  max_priority_fee_per_gas TEXT NOT NULL DEFAULT '1.5',
  is_monitored INTEGER NOT NULL DEFAULT 0,
  custom_abi TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
`;
